### ISSUE TITLE
API to test global shortcuts

### ISSUE THREAD

**Issue by rayrutjes** [electron-userland/spectron#96]
I have window that only shows when a key combination is pressed (`Ctrl+Space` by default).
The behaviour uses electron's `globalShortcut`.

I have found no way of simulating the shortcut, is this possible somehow?

Keep it up!

**Comment by MarshallOfSound** [comment]
@rayrutjes This brings up something I mentioned in another issue somewhere.

> However this raises a point about testing as a whole. Considering the frameworks that electron uses are thoroughly tested both in Electron and upstream in Chromium.

> Do you actually want / need to test that globalShortcut works correctly. What you need to test is that given a function is called with the correct parameters the correct action occurs. For example.

```js
// This is what you need to test
const doThing = () => {
  // Do the thing
};

// This is not
globalShortcut.register('Ctrl+A', doThing);
```

You should assume that the framework you are using (Electron) is tested correctly and test your code does what it should, not that globalShortcut does what it should.

This is all just IMO but it makes sense to me 😆

So you shouldn't be mocking or simulating the shortcut.  Simply call the function the shortcut is associated with. 👍

**Comment by rayrutjes** [comment]
Thank you @MarshallOfSound for your answer. 
I agree with the fact that we shouldn't be testing electron itself. 
In my app, I already have bunch of unit tests. That said, I wanted to test a user scenario:

- When user presses "Ctrl+Space" then the search window becomes visible and the focus should be given to the search input.
- When the user presses enter, a new page should be opened in the default browser and the search window should be closed.

I feel like this is what spectron is aimed at solving, right?  If it isn't, would you be so kind as to suggest a case where spectron makes sense?

I've seen tests where we test the size of the windows, but that brings us back to testing electron.
There also seems to be no way of getting a window based on some kind of unique identifier, which makes the tests brittle if based on `app.browserWindow`.

Some insights about where spectron makes sense would be very much appreciated.

**Comment by blainesch** [comment]
I agree this would be useful, I'm dynamically creating global shortcuts. Testing the action that happens is done, but knowing those shortcuts work in combination and through the stack would be amazing.

**Comment by blainesch** [comment]
I couldn't get this integrated into spectron, but I did manage to get [robotjs](https://github.com/octalmage/robotjs) integrated into my test suite. Using `robot.tapKey()` to test my dynamic keyboard shortcuts.

**Comment by aigarsdz** [comment]
I am facing the same problem. RobotJS is nice and does the job well, but I really don't want to add another dependency just to test a single feature of my app. Any chance for this to be implemented into Spectorn?

**Comment by tansaku** [comment]
@blainesch I really need this functionality - do you have an example of robotjs integrated with spectron so I can copy the setup? many thanks in advance ...

**Comment by blainesch** [comment]
@tansaku spectron and robotjs are used inside of [zazu](https://github.com/tinytacoteam/zazu). Check out the `features/step_definitions` directory for usage.

**Comment by tansaku** [comment]
what I notice though is that robotjs is hitting the computer generally rather than the electron app specifically, so if I start trying to do something else during the acceptance tests, then the change of window focus screws things up.

Would really love to be able to send specific key presses to electron via chromedriver ...

**Comment by linonetwo** [comment]
robotjs is not working for zazu, robotjs don't support node 12 at this time.

I use this to press keys:

```js
  hitKey (key, modifier) {
    if (os.type() === 'Darwin' && !isTravis) {
      const keyForAppleScript = key.length === 1 ? `\\"${key}\\"` : key
      if (modifier) {
        const modifierForAppleScript = modifier.replace('alt', 'option')
        return exec(`Script="tell app \\"System Events\\" to keystroke ${keyForAppleScript} using ${modifierForAppleScript} down"
          osascript -e "$Script"`)
      } else {
        return exec(`Script="tell app \\"System Events\\" to keystroke ${keyForAppleScript}"
          osascript -e "$Script"`)
      }
    }
    const robot = require('robotjs')
    if (modifier) {
      return Promise.resolve(robot.keyTap(key, modifier))
    } else {
      // * will becomes 8, see https://github.com/octalmage/robotjs/issues/285
      const robotjsBadChars = /[~!@#$%^&*()_+{}|:"<>?]/
      let match = key.match(robotjsBadChars)
      if (match) {
        return Promise.resolve(robot.keyTap(key, 'shift'))
      }
      return Promise.resolve(robot.keyTap(key))
    }
  }
```

**Comment by codebytere** [comment]
Closing in light of above workarounds.

**Comment by AdrianoFerrari** [comment]
I recommend this issue be re-opened. None of the above work-arounds work reliably (they've all worked for me at some point, but updates to Node, Electron, or new OS cause them to break, especially on macOS).

Given that Electron apps can and do use global shortcuts, it'd be great to be able to test them. As it stands, I've had to disable testing on macOS, because I can't get spectron to handle global shortcuts like "Cmd+S".

**Comment by coda-nsit** [comment]
I have reopened this issue in light of the comment by AdrianoFerrari
https://github.com/electron-userland/spectron/issues/1010

**Comment by linonetwo** [comment]
The key is not try to trigger a global shortcut, instead listen on a app-level shortcut in your main window, and press shortcut on that window. And send the captured keys to main process, and share the same logic with global shortcut capture. In this way you can test global shortcut's logic, instead of trying to test electron's global shortcut capture infra together.

https://github.com/tiddly-gittly/TidGi-Desktop/pull/642/files#diff-08b06281a2be8fa499abfd3072f502558c587c15bf896d53d74d5e41309e5cd3

https://github.com/tiddly-gittly/TidGi-Desktop/pull/642/files#diff-71ba5da49b7a0c1fe326f05a93cdaadcd74d9afc42a5b476382d5122faa2ef72R32

```ts
function App(): JSX.Element {
  const theme = useThemeObservable();
  useEffect(() => initTestKeyboardShortcutFallback(), []);
```

playwrite + vitest or cucumberjs could do this

https://github.com/tiddly-gittly/TidGi-Desktop/pull/642/files#diff-d7d8a70c73bb57a5f38cb8109f79efe6b26b5a5f11fa808fac287eb969d86fbeR315-R362

```ts
    const event = new KeyboardEvent('keydown', {
      key: mainKey,
      code: mainKey.length === 1 ? `Key${mainKey.toUpperCase()}` : mainKey,
      ctrlKey: modifiers.includes('Control'),
      metaKey: modifiers.includes('Meta'),
      shiftKey: modifiers.includes('Shift'),
      altKey: modifiers.includes('Alt'),
      bubbles: true,
      cancelable: true,
    });

    document.dispatchEvent(event);
```
